# -*- coding: utf-8 -*-
"""CSST-101-MANGULABNAN-MP2

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ksE69DDxH6OLKqeR7d3BO7tVURU1j3ON
"""


# p is the first boolean value and q is the second boolean value

# This perform the AND operation

def and_operation(p, q):
    return p and q

# This perform the OR operation

def or_operation(p, q):
    return p or q

# This perform the NOT operation

def not_operation(p):
    return not p

# This perform the IMPLIES operation

def implies_operation(p, q):
    return not p or q

# This test the logical operations with the sample boolean value

def test_operation():
    p = True
    q = False

    print("AND operation:", and_operation(p, q))
    print("AND operation:", or_operation(p, q))
    print("AND operation:", not_operation(p))
    print("AND operation:", implies_operation(p, q))
    
# Running the test and printing the result

test_operation()